### PR TITLE
Several updates to workflow for curated content started 8/1/2019

### PR DESCRIPTION
**Pull request by bartlettroscoe**
As per we discussed at the BSSw meeting today.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
People should not submit a PR out of thin air. But if they do, then it should be treated like an issue starting in the backlog, moving to "Topic Review" and then "Item Review".

**Comment by rinkug** [comment]
> People should not submit a PR out of thin air. But if they do, then it should be treated like an issue starting in the backlog, moving to "Topic Review" and then "Item Review".

I agree.

**Comment by bartlettroscoe** [comment]
@pagrubel said:

> This step doesn't take care of the case where a PR is sent without going through the other phases, or its not clear to me anyway. 

I added a note on how to handle suggested contributions submitted as a PR instead of an Issue.  Can you please take a look and review & approve the PR if you like.

**Comment by bartlettroscoe** [comment]
@markcmiller86, can you merge in the updated 'master' branch and fix merge conflicts and push back to branch?

**Comment by markcmiller86** [comment]
Ok, this just got merged as #406

**Pull request closed without merging**
