### PR TITLE
National RSE Organizations

### PR DESCRIPTION
**Pull request by rinkug**
Author: Rinku

Refers to issue #432

### CODE REVIEW

**Comment by bernhold** [comment]
This is a work in progress PR. Not ready to merge.  Moving back to In Progress

**Comment by rinkug** [comment]
I will wrap this up soon!

**Comment by pagrubel** [comment]
I don't understand why there is a pull request.

**Comment by markcmiller86** [comment]
> I don't understand why there is a pull request.

@pagrubel I think this is *work in progress* PR. So, it is a partially completed CC article that @rinkug plans to finish up soon.

Note to everyone, for a *work in progress* PR, you *can* declare the PR to be in a *draft* state when you create it by pulling down to **Create Draft Pull Request**

...

When you do this, if you assigned any reviewers, they will not get pestered to do a review until you change the state of the PR from *draft* to *final*.

**Comment by rinkug** [comment]
@pagrubel This article is done and needs a review from you to wrap up

**Comment by pagrubel** [comment]
I made some minor changes.

**Comment by rinkug** [comment]
This is published.

**Pull request merged**
