### PR TITLE
Initial commit of telecon tool features/uses

### PR DESCRIPTION
**Pull request by markcmiller86**
* capture some notes
* play with table format a bit

### CODE REVIEW

**Comment by markcmiller86** [comment]
@maherou if you have some time, if you could have a look at this PR and see if there are features missing you think should be included or features there you think aren't too relevant. This is based on conversation from yesterday. You can inspect the rendered markdown at [this link](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/mcm86-cc-teletools-4-remote-work/CuratedContent/TelecomToolsForRemoteWork.md)

**Comment by jarrah42** [comment]
Here's what we're using. Feel free to take whatever you think is useful:

Capabilities
--
- Whiteboard
- Shared whiteboard
- Annotations
- Screen sharing
- Desktop/application sharing
- Recording/playback
- Calendar integration
- Scheduled meetings
- Group chat
- Individual chat
- Breakout sessions
- Speaker tracking
- Gallery view
- Video pinning
- Outside users
- File sharing
- Reactions/polling
- Virtual backgrounds
- Personal meeting IDs
- Meeting limit
- Meeting time limit
- Other

Security
--
- Random meeting IDs
- Encryption
- Meeting locking
- Pariticpant removal

A/V Features
--
- Max participants
- Audio quality
- Video quality
- Dial-in available
- Dial-in linked to video feed (e.g. "Call me")

Platforms
--
- Windows
- MacOS
- Linux
- iOS
- Android
- Browser

Licensing
--
- Basic
- Intermediate
- Enterprise

User experiences
--
- Maximum number of participants successfully experienced
- Maximum number of participants successfully hosted
- Years of experience as user
- Reliability as experienced by real users

Ease of Use
--
- International phone numbers
- Easy phone entry for participants
- Easy video entry for participants
- Call back support
- Easy entry without individual host approval

**Comment by rinkug** [comment]
@markcmiller86 I can help you with curated content formatting etc. That way,  you can focus on the content.

**Comment by bartlettroscoe** [comment]
@markcmiller86, can we add a row for remote keyboard and mouse control?  That is critical for remote pair-programming.  I know that WebEx and Skype for Business supports that but I don't think that Bluejeans does.

**Comment by bartlettroscoe** [comment]
@markcmiller86, might also be nice to add a column for Skype (for Business) since that is that is the current required solution for SNL.

**Comment by bkmgit** [comment]
The overview is nice.

One feature that may be helpful to add is how scalable a solution is, eg. is it good for upto 10 people, 50 people, 100 or more people. 

It may also be helpful to include open source options such as
* [Jitsi](https://jitsi.org)
* [Apache Open Meetings](https://openmeetings.apache.org/)
* [Big Blue Button](https://bigbluebutton.org/)
* [OpenVidu](https://openvidu.io/)

Since WebRTC makes streaming video over the web easier than it was before, video chat applications can also work for small group meetings, as for example done in:
* [Nextcloud](https://nextcloud.com)

Some of these can be readily deployed, for example see https://aws.amazon.com/marketplace/pp/Code-Creator-Jitsi-Meet-Video-Conferencing/B081QH7V6V  (link is an example not an endorsement)

Other solutions include
* [Eztalks](https://www.eztalks.com)
* [Ding Talk](https://www.dingtalk.com/en/)
* [Google Hangouts](https://hangouts.google.com/)

**Comment by markcmiller86** [comment]
@bartlettroscoe will work on Skype column. Don't work on it until you get heads up from him that he is done.

**Comment by bkmgit** [comment]
Building own solution may also be possible using for example
* https://www.alibabacloud.com/product/apsaravideo-for-live
* https://aws.amazon.com/solutions/live-streaming-on-aws/
* https://cloud.google.com/solutions/media-entertainment/use-cases/live-streaming/
* https://docs.microsoft.com/en-us/azure/media-services/latest/live-streaming-overview

**Comment by markcmiller86** [comment]
@elaineraybourn found this great PDF we should somehow included either here or as an additional CC

[VirtualConferences_GuideToBestPractices_CURRENT.pdf](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/files/4506932/VirtualConferences_GuideToBestPractices_CURRENT.pdf)

**Comment by elaineraybourn** [comment]
Hey @markcmiller86, by the way, I've had several requests to share this ACM document with a broader audience--so what do you think about me creating a resource page such as https://bssw.io/items/resources-for-maximizing-remote-working for virtual conferences? Would this augment your efforts, or should I wait until your article is live to point folks to that link? I'm flexible.

**Comment by markcmiller86** [comment]
@elaineraybourn ... please feel free to move foward as another resource.

**Comment by elaineraybourn** [comment]
@markcmiller86 sounds good. I'll work on a pointer that perhaps mention ACM as having good resources for virtual events like conferences--so slightly expanding the topic so it doesn't distract from your article. I'll work with @rinkug for guidance on how to handle.

**Comment by markcmiller86** [comment]
Well, I am curious...if this is going to take a week to put in place, I guess I'd prefer we just include it in what I am putting together. I am committing some more changes to that PR this PM. Maybe its close enough to be read to host with the intention of adding to it (e.g. evolving it) as BSSw-EB decided would be appropriate.

**Comment by markcmiller86** [comment]
@betterscientificsoftware/editorial-board I need the following help to complete this...

1. Can anyone with experience with any of these tools for the [use-cases](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/mcm86-cc-teletools-4-remote-work/CuratedContent/TelecomToolsForRemoteWork.md#experiences-in-actual-use) described fill in any boxes in the *subjective* quality section (bottom of table)? I've filled in from my experiences with Zoom (recent) and WebEx (past 4+ years).
1. Can anyone pick a *row* (or *rows*) to try to fill in? The way I have done this is to submit the same search *query* on Google using their [URL search *keywords*](https://moz.com/blog/the-ultimate-guide-to-the-google-search-parameters) but with time restricted to *last month* and different product names as in...

```
https://www.google.com/search?q=security+issues+with+webex+video+conferencing+software&as_qdr=m
https://www.google.com/search?q=security+issues+with+zoom+video+conferencing+software&as_qdr=m
https://www.google.com/search?q=security+issues+with+gotomeeting+video+conferencing+software&as_qdr=m

```

**Comment by markcmiller86** [comment]
Oh, and, of course, I need someone to a) review what is there...there are many typos I think and maybe b) suggest additional links to point to from each sub-sub-section heading.

**Comment by bartlettroscoe** [comment]
@markcmiller86, @rinkug, @curfman,

It occurred to me that since I have been looking into these tools recently and found out that:

* MS is dropping support for Skype for Business in [July 2021](https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/skype-for-business-online-end-of-life-july-31-2021/ba-p/779137)

* Sandia will be switching from Skype for Business in to MS Teams in 2021

* Skype for Business has a lot of problems and missing features compared to other tools already listed

that perhaps we should not bother providing a column in this table for Skype for Business since no one in their right mind would select Skype for Business given other choices.

But perhaps we should at least mention that Skype for Business exists and mention that it is currently being used by some institutions and that the current plan is for MS to end support for Skype for Business in July 2021.  Then we should suggest that teams that might be interested in Skype for Business should instead look at MS teams?

What do you think?

**Comment by markcmiller86** [comment]
I can't recall who suggested we needed the Skype for Business column in the first place. So, its fine removing it. That said, 2021 is a long way in the future and I can envision some subset of our readership having an interest in it. All of the information you provided above can be included as *product footnotes* (as you can see there for other products).

**Comment by bartlettroscoe** [comment]
> I can't recall who suggested we needed the Skype for Business column in the first place.

@markcmiller86 it was me :-(

>  All of the information you provided above can be included as product footnotes (as you can see there for other products).

Right, but how about we just have a section that mentions other tools not included in the table and provide a few bullets about them below that in the footnotes?

After some thought, I think we should only be including columns in that table for products that we think people should seriously consider using if they have a choice.  (The issue is that some people don't really have a choice in many cases as it is dictated by their company.)

**Comment by markcmiller86** [comment]
@bartlettroscoe I see you most recent commit there and read the footnootes...AFAICT that second note about *browser* behavior is pretty much true across the board. A browser often requires an extension or plugin installed (but that is sometimes less involved for a powerless user than installing a whole application) and typically then does not support all the sharing features.

**Comment by bartlettroscoe** [comment]
BTW, does everyone know how to use GitHub as a WYSIWYG for markdown files?  You can do that through a separate branch in your GitHub fork and then you can be editing the Markdown file on your locally machine and then just do:

```
$ git commit --amend -a --no-edit \
   && git push -f rab-github mcm86-cc-teletools-4-remote-work:mcm86-cc-teletools-4-remote-work
```

You can see the WIP rendering at:

* https://github.com/bartlettroscoe/betterscientificsoftware.github.io/blob/mcm86-cc-teletools-4-remote-work/CuratedContent/TelecomToolsForRemoteWork.md

Otherwise, I can't image the nightmare it must be trying to edit a Markdown file like this.

**Comment by markcmiller86** [comment]
You can also do one of the following...

- Edit the file directly on GitHub from any browser and use the **Preview** tab.
- Use the markdown extension in Google chrome to render locally called Markdown Viewer available in the Google Chrome Store.

**Comment by bartlettroscoe** [comment]
> Use the markdown extension in Google chrome to render locally called Markdown Viewer available in the Google Chrome Store.

@markcmiller86, thanks for the tip.  It takes a little configuration but the "Mardown Viewer" Chrome extension looks pretty nice.  Thanks!

**Comment by rinkug** [comment]
This is done and published.

**Pull request merged**
