### PR TITLE
Personal Kanban curated content

### PR DESCRIPTION
**Pull request by pagrubel**
Author: Pat
EB member: Rinku

Wrote curated content for issue #418 on using Personal Kanban
@rinkug I assigned you but anyone can review it.

### CODE REVIEW

**Comment by rinkug** [comment]
Pat, I added an existing example for a resource table declaration for a web article: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/rinkug-wrokflow-documentation/Documentation/StyleGuide/StylingCuratedContent.md#web-article

**Comment by pagrubel** [comment]
@rinkug Used the new entry to your guide. How does that look?

**Comment by bernhold** [comment]
@rinkug please check metadata and then it should be ready to publish

**Comment by rinkug** [comment]
This is merged and is online now

**Pull request merged**
