### PR TITLE
What you can do to help stop the spread

### PR DESCRIPTION
**Pull request by markcmiller86**
Here's a draft of a blog article I think might be relevant.

### CODE REVIEW

**Comment by markcmiller86** [comment]
Thanks @jarrah42 ... did anything strike you *missing*?

**Comment by markcmiller86** [comment]
I've made a number of minor changes since original draft.

Remember, *just before* we try to publish, we need to run `wikize_refs.py` on it.

The final hero image is excellent! and its CC licensed.

**Comment by curfman** [comment]
Excellent article, Mark.  Thank you for writing this.  I'll run wikize_refs and make a preview.

**Comment by markcmiller86** [comment]
Thanks @curfman. I just tried running wikize_refs myself and ran into a slight problem. Am looking into cause now.

**Comment by markcmiller86** [comment]
Ok, I have fixed for wikize ref gen. The problem was that I didn't correctly format a few of the footnote refs in the original `.md` file. But, this also revealed a couple of unused refs which I also added. 

Should be good to go now.

**Comment by rinkug** [comment]
This has been published in Mar 2020

**Pull request merged**
