### PR TITLE
Link to Site/CuratedContentEditorialWorkflow.md from HowToContribute.md

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @rinkug, @curfman, @markcmiller86 

That page Site/CuratedContentEditorialWorkflow.md is currently titled "A Proposed Alternative Editorial Workflow for BSSw.io Curated Content".  But we spent a lot of time on that so should we just make that the process?  It is better than the current process of "Create your contribution!".

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
We should also update the page Site/CuratedContentEditorialWorkflow.md to change the title from "A Proposed Alternative Editorial Workflow for BSSw.io Curated Content" to "Editorial Workflow for BSSw.io Curated Content".

**Comment by bartlettroscoe** [comment]
@curfman and @rinkug, this PR may be invalid given the untracked activity of setting up a new "how to contribute" page on the BSSw site.  I will let you figure this out.  It is just that we keep taking about "the process" but there is no official editorial process according to these documents.

**Comment by rinkug** [comment]
We now have a new and clear contribution process on https://bssw.io/pages/what-to-contribute-content-for-better-scientific-software

@bartlettroscoe : If you agree, this PR is no longer needed and can be closed?

**Comment by bartlettroscoe** [comment]
@rinkug, I still can't find any links to the actual process [BSSw Contibution Editorial Process](Site/CuratedContentEditorialWorkflow.md) for :

* https://bssw.io/pages/what-to-contribute-content-for-better-scientific-software
* https://bssw.io/pages/how-to-contribute-content-to-better-scientific-software

or the instructions in a new issue:

* https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/issues/new?labels=curated+content+ideas&template=curated-content.md&title=Possible+Curated+Content

Where is the link to [BSSw Contibution Editorial Process](Site/CuratedContentEditorialWorkflow.md)?

Contributors should be able to to see the actual process if they want to see it.

**Comment by bartlettroscoe** [comment]
CC: @markcmiller86 

@rinkug, @curfman, @bernhold,

Did the text provided in:

* https://bssw.io/pages/how-to-contribute-content-to-better-scientific-software

go through some type of review process by the EB members?  I don't remember seeing this before it was published.

I am reading this and it does not seem to make sense.   In the "Simple approach via Google form submission", what is the author supposed to be submitting?  Is this supposed to just be the idea for an article or the entire article?  The instructions at the bottom:

> **What happens next?**
> After your issue is submitted, it will be reviewed by the BSSw.io editorial team. We will communicate with you to provide feedback and determine next steps, including a timeline. To proceed with publishing content on the BSSw site, you will be asked to create a Git pull request, which facilitates review and revision of the article before it is published. **Alternatively, if you are unfamiliar with Git, the BSSw team will work with you to get your article through email or other methods.**

That would suggest that only the idea for a contribution should be submitted via the Google Form or that last part makes no sense.  But clearly people think they are supposed to submit the entire article via the Google form because that is what happened with   #375 and #424.

**Comment by rinkug** [comment]
@bartlettroscoe : Why do they need to see the entire editorial process? Its not something authors should care about? If they are curious, they are  dig deeper in the git repo and easily find it. IMO, keep things as easy as possible for contributors

**Comment by bartlettroscoe** [comment]
> Why do they need to see the entire editorial process? Its not something authors should care about. If they are curious, they are dig deeper in the git repo and easily find it. IMO, keep things as easy as possible for contributors

Because they have the right to know what their contribution will be subjected and there should not be any surprises once they do submit.   You don't make this the thing they are told to look at but you given them a link in case they are curious.  Are we trying to hide something?

Also, letting people see that a careful editorial process is being used may give them confidence that it is worthwhile to submit something because they will know that it will be with other quality submissions.

Just my opinion.  I have said my piece so I will close

**Comment by jarrah42** [comment]
All the online publishing sites I looked at made it easy to see the editorial process. Also, it lets them know what they're in for...

**Comment by markcmiller86** [comment]
FWIW, I agree with @bartlettroscoe and @jarrah42 ... the process should be as fully transparent as possible for the interested. We should NOT force them to review it but we should offer a link if they ever want to know.

**Comment by markcmiller86** [comment]
@bartlettroscoe, I have filed #433 in response to your concerns [here](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/pull/410#issuecomment-543729535). 

But, I would also like to encourage/empower *everyone* on the team to rather than engaging in lengthy issue dialog just please go ahead and submit a PR to make a change that so obviously needs to happen. I think that will often be faster than through an issue Q&A.

**Comment by rinkug** [comment]
> FWIW, I agree with @bartlettroscoe and @jarrah42 ... the process should be as fully transparent as possible for the interested. We should NOT force them to review it but we should offer a link if they ever want to know.

I agree providing a link to the editorial process in reasonable. @bartlettroscoe : I saw your edit and when the edit itself looks fine, your branch contains an old version of How-to-contribute.md file

**Comment by rinkug** [comment]
> > FWIW, I agree with @bartlettroscoe and @jarrah42 ... the process should be as fully transparent as possible for the interested. We should NOT force them to review it but we should offer a link if they ever want to know.

@bartlettroscoe A added a pointer to the editorial process at https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/HowToContribute.md
Note that our editorial process just talks about curated content for now.

**Comment by rinkug** [comment]
> That would suggest that only the idea for a contribution should be submitted via the Google Form or that last part makes no sense. But clearly people think they are supposed to submit the entire article via the Google form because that is what happened with #375 and #424.

The how-to-contribute page and google form now has clear instructions that only the abstract needs to be submitted.

**Comment by bartlettroscoe** [comment]
>The how-to-contribute page and google form now has clear instructions that only the abstract needs to be submitted. 

When I read the updated page:

* https://bssw.io/pages/how-to-contribute-content-to-better-scientific-software

and see the text:

> PLEASE NOTE that at this stage, you are expected to only submit a short abstract of your article. Once reviewed and if accepted, you will be contacted to submit the complete version. Once you are ready to contribute, please use one of the below approaches to submit your article.
>
> Submission via Google form
If you are not familiar with GitHub, you can submit your content using the Google form.

it makes me think that the author is expected to submit the full article using the Google form.  So I am still confused.

**Comment by rinkug** [comment]
This was completed and closed AFAIK.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Pull request closed without merging**
