### PR TITLE
Create TenRulesToBuildACommunity.md

### PR DESCRIPTION
**Pull request by markcmiller86**
Author:Mark Miller

### CODE REVIEW

**Comment by junghans** [comment]
Thanks!

**Comment by bartlettroscoe** [comment]
@markcmiller86, is this ready to review?

Also, what is the associated GitHub Issue as per the process:

* https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/CuratedContentEditorialWorkflow.md

which says:

> Authors submit Pull Requests (PR) for completed work
> * Add GitHub issue `#<issue-id>` to PR comment (to link PR and Issue).

?

**Comment by markcmiller86** [comment]
@bartlettroscoe ... I didn't add an issue. I was sent a great article by @junghans, read it in its entirety, and decided on the spot to write a quick CC article for it. And, I am guessing it takes less time to do that and have others decide what to do with it than to first submit an issue, then wait for dialog and up or down votes, then wait for it move through to the ready-for-development state and then remember to write it.

**Comment by bartlettroscoe** [comment]
@markcmiller86 

> I didn't add an issue.

Okay

> And, I am guessing it takes less time to do that and have others decide what to do with it than to first submit an issue, then wait for dialog and up or down votes, then wait for it move through to the ready-for-development state and then remember to write it.

If an EB member likes a piece of content (and is not just publishing their own work), then I don't see problem with this.  Do we want less stuff on BSSw?

But we should likely get them to change to process to allow this shortcut workflow.

**Comment by bernhold** [comment]
I've opened a separate issue (#439 ) for the higher-level discussion about the general idea of accepting PRs without topic review, etc.

**Comment by pagrubel** [comment]
If this is by @junghans why not add him as a contributor to the article?

**Comment by markcmiller86** [comment]
It is not *by* @junghans. I wrote the CC article. @junghans simply brought it to my attention.

**Comment by bernhold** [comment]
We want all articles to acknowledge the contributors.  So either you, or you and Christoph, I think should be listed.  We don't have to be *that* rigorous about who to include as contributors, as long as it is reasonable.

**Comment by rinkug** [comment]
@markcmiller86  and @bartlettroscoe : Status on this one?

**Comment by markcmiller86** [comment]
This is ready. I would merge to master myself. However, if I do *without* necessary metadata block, I fear it will fall through cracks. These are the last steps (6 & 7) in our workflow.

I don't know who should add the metadata block and what it should look like, in particular, key words and categories. Are those listed somewhere?

**Comment by bernhold** [comment]
I added metadata.  I put it in the `topic` "Strategies for More Effective Teams".  The topics are exactly what you see on the production site.  We also have a `categories` metadata field, but it is now ignored, since they can be derived from the topics.

I adjusted the contributor links to point to the users' GitHub profiles rather than their entry in the organization team listing.

I merged, checked in preview, and have now marked the article for publication.  It will appear when the production site is next rebuilt. (Thursday at the latest, since we're publishing a blog article then.)

**Pull request merged**
