### PR TITLE
Container Mythbusters curated content

### PR DESCRIPTION
**Pull request by pagrubel**
Content for curated article on video "Container Mythbusters"
satisfies issue #401

### CODE REVIEW

**Comment by rinkug** [comment]
Pinging @bartlettroscoe on this. Since this is a busy time, let us know if you need help with this

**Comment by bartlettroscoe** [comment]
@pagrubel, why was PR #401 closed and this new one opened?

**Comment by pagrubel** [comment]
@bartlettroscoe That was what I thought #5 of 
Site/CuratedContentEditorialWorkflow.md instructed the author to do
Create a pull request that references the issue and close the issue.

**Comment by bartlettroscoe** [comment]
> why was PR #401 closed and this new one opened?

Sorry, I got confused.  I could have swan that I reviewed a PR for this content.

Please let me know when this is ready to review.

**Comment by pagrubel** [comment]
@bartlettroscoe I think its ready for review and can be published if you think all is well.

**Comment by rinkug** [comment]
This is now published: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/ContainerMythbusters.md

**Pull request merged**
