### PR TITLE
Defensive Coding Article from Wolfgang Bangerth, discussed at CW3S19 workshop.

### PR DESCRIPTION
**Pull request by bernhold**
Based on discussions at CW3S19 workshop with @bernhold and @curfman.

### CODE REVIEW

**Comment by bernhold** [comment]
Plan to use Blog_032420_StoneMasonry.png for the hero.

**Comment by rinkug** [comment]
Does this have an issue? If not, David or I can open a (very brief) issue ticket to link to this PR.

**Comment by bernhold** [comment]
@rinkug If we have the PR, why do we need an issue too?  Our process works perfectly well for PRs in lieu of issues.  This one entered the process at the stage of having draft text, so it seems perfectly reasonable to me to just have the PR.

**Comment by bernhold** [comment]
Published!

**Pull request merged**
