### PR TITLE
Add first draft of xSDK community polcies blog post

### PR DESCRIPTION
**Pull request by luszczek**

### CODE REVIEW

**Comment by bernhold** [comment]
:+1:  I quite like it. 

I would suggest swapping the first two sentences, as I think the second makes a better deck. Related possibilities include merging the two into a single paragraph (after the swap), however this might make the deck longer than desirable. Or just deleting what is currently the first sentence.

**Comment by bernhold** [comment]
Note: in issue #393, Piotr mentions a related PR for the hero image: https://github.com/betterscientificsoftware/images/pull/4

I'm noting it here in anticipation of this thread superseding the issue.

**Comment by curfman** [comment]
Piotr and Ulrike -- Very nice article -- clear explanation of xSDK policies and considerations.  This will be a valuable resource for the community.  

One request: shorten bios to 50-100 words max per author.  Length: 50-100 words (paragraph form), can include hyperlinks. Mention your current position, employer, a bit about your background. Include info about your interests related to software productivity and sustainability. Anything else you want to mention.

**Comment by rinkug** [comment]
Published at https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/BuildingCommunitySoftwarePolicies.md

**Pull request merged**
