### PR TITLE
Windus MolSSI blog article for early November

### PR DESCRIPTION
**Pull request by bernhold**
This is a light revision of a whitepaper from the CW3S19 workshop, being jointly published by URSSI and BSSw.

Next step is for @gpieper to make an edit pass.

Hero image under discussion separately.

### CODE REVIEW

**Comment by bernhold** [comment]
Corrected a mistake on the label.  No idea how that happened.

**Comment by bernhold** [comment]
@curfman indicated her approval in email.  Needed to merge so that Matt/SBX can work on the image.

**Comment by bernhold** [comment]
Preview approved by author.  Ready to publish.  Planned for 14 Nov.

**Comment by rinkug** [comment]
Published at https://bssw.io/blog_posts/software-sustainability-in-the-molecular-sciences

**Pull request merged**
