### PR TITLE
Create DeepWork.md

### PR DESCRIPTION
**Pull request by jarrah42**
Author: jarrah42 
Author: Greg Watson

This is a PR for the Deep Work CC article
See Issue #417

### CODE REVIEW

**Comment by jarrah42** [comment]
As far as I can tell, this is just waiting for approval and to be merged.

**Comment by rinkug** [comment]
@jarrah42 : Made a few changes to text and formatting. Please review and revise, if needed.. When done, we can go ahead  and publish it.

**Comment by jarrah42** [comment]
> @jarrah42 : Made a few changes to text and formatting. Please review and revise, if needed.. When done, we can go ahead and publish it.

The changes look fine.

**Comment by rinkug** [comment]
This was published today at https://bssw.io/items/a-look-into-rules-for-focused-success-in-a-distracted-world

**Pull request merged**
