### PR TITLE
Bad PR with worthless merge commit

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Bad commit to demonstrate worthless merge commit created by bad GitHub web usage

This commit was created using the process described at:

 https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

Note the worthless commit commit bartlettroscoe@6a97a21.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
This was just an example to demonstrate what happens if you follow the process at:

* https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

and then create a branch and a PR off of that.

Closing because we don't want to merge.  I just wanted to demonstrate the point.

**Comment by markcmiller86** [comment]
@bartlettroscoe I followed those same instructions to success. Though, the first time I tried using a different set of instructions and wound up doing a merge back to upstream master. So, not sure what you are demonstrating.

I was demonstrating it is possible to use web interface to sync a fork'd branches master with upstream. It is a little more involved than I'd like but it seems to work. And, I think its the wrong thing to force would-be authors who may not also be software developers to use git command-line to draft and revise content.

**Comment by bartlettroscoe** [comment]
@markcmiller86, it took a lot of clicks to get this PR created and it was not straightforward.   After you create the branch, you have not abandon the PR it tries to make you create and you instead of to go to the list of branches in your fork, select your new branch, and then click the "Compare and Create Pull Request" button and select the target repo as the main BSSw.io repo.  Lots of jumping around.  Kind of silly.  But I can document the 15-step click-click-click process :-)

**Comment by markcmiller86** [comment]
Honestly, don't wanna burden you with documenting all that. We don't really have any non-software developer contributors yet, do we? I agree, documenting all that is needed, at some point. I am not sure it is necessary *now*.

But, if you are willing, that would be great. I think capturing what is going on for a non-software content creater who may be only a technical writer (I don't mean only as in somehow less than developer way but only as in not wanting to deal with the perspectives of a developer) is useful. Maybe another option to address this workflow is suggest best GUI tool(s) to run locally.

Why can't we *clone* a repo on github web itself? Why do we have only the fork option there?

**Comment by bartlettroscoe** [comment]
@markcmiller86,

I can list out the steps for this.  Should we split the instructions for updating the 'master' branch in a fork separately?

**Comment by markcmiller86** [comment]
> I can list out the steps for this. Should we split the instructions for updating the 'master' branch in a fork separately?

I think that makes sense. That is really an aspect to the tools being used to develop the content and not at all related to the actual content development itself, right? I mean this need to update the master on a fork'd repo is not something anyone doing normal MS Word collaboration would ever be hit with.

**Pull request closed without merging**
