### PR TITLE
Adding an issue template for events

### PR DESCRIPTION
**Pull request by markcmiller86**
I propose the following template for events.

Part of the reason of constraining the format of this issue is to make it very easy to go from the markdown submitted here as an issue to whatever form(s) the event needs to be *published* as either on BSSw calendar, etc.

### CODE REVIEW

**Comment by bernhold** [comment]
Hmmm,  I made (extensive) changes to Mark's PR, and a comment with that commit.  The changes do appear in the PR, but I had expected the comments to appear in this conversation and they're not (I can drill into the "Commits" portion of the PR and see my comments there).  So what's the right way to propose changes directly to a PR?

**Comment by bartlettroscoe** [comment]
@bernhold asked:

> So what's the right way to propose changes directly to a PR?

You are referring to commit 68d72fcef183eb36c45aa26e41487c2823649505, right?

That is the way GitHub works.  Since you comments are in the new commit, there is no need to duplicate them in the PR issue.

**Comment by bernhold** [comment]
No doubt, but right now, to be perfectly honest, I do events by trial and error and I'm not really sure what is supported.  There is a long-standing need for documentation as to how the frontend is processing things.  I've noted that elsewhere.

We can definitely look in the existing events and pull out some examples that are known to work.  They just won't necessarily show the full range of possibilities.

Where do you think examples are most needed?  I think dates?  Anything else?
________________________________

**Comment by bernhold** [comment]
Yeah, that's the commit.

But those comments are buried.  If you look only at the main PR conversation, you don't even see an indication that anything has changed since Mark's original submission.  The only think I could see that changed was the number of commits constituting the PR.  Did a notification of my commit go out?
________________________________

**Comment by bartlettroscoe** [comment]
@bernhold said:

>  If you look only at the main PR conversation, you don't even see an indication that anything has changed since Mark's original submission. 

No, it is in the feed above if you look.  Here is my screen shot:

image

> Did a notification of my commit go out?

Yup.  The email I got is shown below.  You don't get an email because GitHub assumes you know that you pushed a new commit :-)

----

**Comment by markcmiller86** [comment]
@bernhold ... I guess we are aiming at different goals and making different assumptions.

First, any text that appears in the issue template is, in all likelihood going to appear in the issue submission. Submitters often forget to remove that boilerplate text. So, I see value in *minimizing* as much as possible the boilerplate text. Worst case, I think it is much better to have all this instructive text somewhere *other* than the issue template itself and just link to it.

Next, my assumption is that anyone can understand the very short instruction

> replacing *italicized text* with actual event information and without adding or removing lines

sufficiently to submit quality information.

**Comment by bernhold** [comment]
> @bernhold ... I guess we are aiming at different goals and making different assumptions.
> 
> First, any text that appears in the issue template is, in all likelihood going to appear in the issue submission. Submitters often forget to remove that boilerplate text. So, I see value in _minimizing_ as much as possible the boilerplate text. Worst case, I think it is much better to have all this instructive text somewhere _other_ than the issue template itself and just link to it.
> 
> Next, my assumption is that anyone can understand the very short instruction
> 
> > replacing _italicized text_ with actual event information and without adding or removing lines
> 
> sufficiently to submit quality information.

Maybe not *so* different.  I tried to provide the itemize list of info that we need and to keep those descriptions very short.  

The rest of it probably needs to be documented *somewhere*.  I am completely open to the idea that the issue template may not be the right place.  But at the moment, it is what we have.  I have found the frontend to be picky enough (or my understanding of it poor enough) that I do think these details and perhaps examples, as Ross suggested, will need to be close at hand for the submitter if we're to have a hope of getting something usable out of the submission.

I also had in the back of my mind the thought that if we expect to have a script to process the issue into a (draft) event, maybe that script could key on the itemized list and strip out the remainder of the instructions.

**Comment by markcmiller86** [comment]
> I also had in the back of my mind the thought that if we expect to have a script to process the issue into a (draft) event

Ah, ok, maybe that is where I was thinking differently. With a script to help process, I agree, we can be less concerned about format and/or content of the template itself. 

I had been aiming for something where a simple cut-n-paste from the issue to its intended destination would be all that was needed to be done by an **EB Member** to *publish* the event.

**Comment by pagrubel** [comment]
Having read through all of this conversation and looking at  WhatToContribute.md 
I really can't add all that much except I agree Events should be fairly easy to get on the site without too much process. 
Why not put What Is and How To articles in subfolders? Seems to make it a little clearer. I'd even like to see those clearer on the actual site, but I have been gone and haven't gotten to look at it yet (next on my list).
I'll look back at the templates to see what has changed if anything and comment further.

**Comment by pagrubel** [comment]
This looks good to me. Some of the text might be unnecessary, but hard to say until we practice using it as an actual template. For now I can just view the md file which is probably fine

**Comment by pagrubel** [comment]
Can I merge this there are two approvals?

**Comment by markcmiller86** [comment]
I am not seeing the need for all the changes that were made here. For comparison purposes, the image I attach here shows the original and final versions side-by-side. Even so, the bottom got cut off the right hand version because it is so long. Its way too complicated now and I don't think all the text here will serve the purpose it was intended

issue_compare

**Comment by markcmiller86** [comment]
This PR has been sitting ready for a while. Sorry I neglected it. Merged now.

**Comment by rinkug** [comment]
Thanks @markcmiller86. Glad we have an event template now. I didnt know we had a PR for it  :)

**Pull request merged**
