### PR TITLE
Create LackOfEvidenceInSoftwareEngineering.md

### PR DESCRIPTION
**Pull request by jarrah42**
Author: Greg

PR for issue #420 (Lack of Evidence In Software Engineering)

### CODE REVIEW

**Comment by markcmiller86** [comment]
@prwolfe ... did this fall of your radar?

**Comment by rinkug** [comment]
@jarrah42 @prwolfe :  Is this ready to be merged?

**Comment by jarrah42** [comment]
Yes

**Comment by prwolfe** [comment]
agreed

**Comment by rinkug** [comment]
I gave this a look and it needs more work: (1) deck to be created, (2) table to be moved to correct position, (3) Description to be cleaned up? 
I will work on this.

Note for Rinku and Lois: The curated content style needs to be reviewed for completion and its use needs to be encouraged.

**Comment by bernhold** [comment]
Would like to have this published by 2020-05-22.

**Comment by jarrah42** [comment]
The scientific method is the cornerstone that underpins how science leads to the advancement of human knowledge. Yet the use of rigorous empirical methods, such as double-blind randomized control trials, have not been extensively used to evaluate the benefits of programming language features. Considering the impact that software has on our society, addressing this deficiency should be a priority.

**Pull request merged**
