### PR TITLE
Rate your project blog

### PR DESCRIPTION
**Pull request by jarrah42**

### CODE REVIEW

**Comment by markcmiller86** [comment]
Hi @jarrah42 ... not sure where you are at in the development of this content but its looking great! The only thing I might suggest is to mention how the act of going through the scoring process also helps to start dialog about practices and about how where those practices *fit* in the larger context of modern, tech-industry established software processes.

I also think your particular *relaxed* and uncontroversial style of guiding the Q&A process to help a team decide on where it landed on a particular practice was *essential* to creating the right climate for a candid discussion about a team's processes.

**Comment by markcmiller86** [comment]
Oh, and without giving away project names, maybe offer a summary of where many projects tended to land and which practices are many projects commonly weak on.

**Comment by jarrah42** [comment]
Hi Mark, thanks for the feedback! This was just a first draft, so I'll incorporate your suggestions into the next version.

**Comment by rinkug** [comment]
PR #477 is the follow on PR for this

**Pull request closed without merging**
