### PR TITLE
Improve documentation on content types

### LINKED ISSUE #361: Review Content Types and What They Mean
### BSSw Sub-Comittee Homework Assignment Due May 30, 2019
Before we continue developing editorial *workflow* for various types of content, we should probably review the content types we have, decide if we need to adjust the set of types we wanna support and also identify what criteria we use to determine what a given content type is or any specific requirements it may have.

This issue is about having that conversation.

Our current content types are described in our [What To Contribute as of May 23, 2019](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/91648f8f992639ad8a9f5467e00cf6dc1bec21a7/WhatToContribute.md) document. So, lets go review that first. After revewing that, add comments/discussion here about this. One key question that has come up recently is whether we have a few different types of *articles* and not just *blog* articles.

When you have finished with your commentary, etc. on this topic, please check your name off the following list...

- [ ] @rinkug 
- [x] @markcmiller86 
- [x] @pagrubel 
- [ ] @prwolfe 
- [ ] @curfman 
- [ ] @bernhold 
- [x] @bartlettroscoe 
- [ ] @JeanShuler

### PR DESCRIPTION
**Pull request by markcmiller86**
This is a **DRAFT** PR.

Resolves #361 when finalized.

[View the proposed file itself](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/markcmiller86-content-types-doc/Site/ContentTypes.md)

### CODE REVIEW

**Comment by jarrah42** [comment]
I like David's use of "Original" rather than "Article". It also makes more sense when you're talking about content _type_.

**Comment by bernhold** [comment]
Technically, my term was "original article".  I notice @markcmiller86 also shortened "curated content".

I think that internally, we all understand these things and can recognize the abbreviations.  I think the question is what terminology do we want to use in public, for example in the <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/WhatToContribute.md> page.

I'd vote for the full terms in both cases.

**Comment by markcmiller86** [comment]
Why is *content* only combined with the type **Curated**? It seems to me that we either have **Event Content**, **Curated Content**, and **Article Content** or we have the content types, **Event**, **Curated**, **Article**. I see this like I see code, we don't have **int type**, **double type** and **float type**. We have the types whose names are **int**, **double** and **float**.

Next, I'm not too sure why we'd need an *originality* attribute for an **Original Article** content type. If our types are to be **Event**, **Curated Content** and **Original Article**, I suspect the *originality* attribute can be dropped as it really provides no new distinguishing aspect; **Event** and **Curated Content** are, typically, low originality and **Original Article** is not low originality which I think are also easily inferred from their names.

All that said, indicate your vote by checking box under the desired type names below

- **Event** / **Curated** / **Article**
  - [ ] @bernhold 
  - [ ] @jarrah42 
  - [ ] @pagrubel 
  - [ ] @curfman 
  - [ ] @rinkug 
  - [ ] @bartlettroscoe 

- **Event** / **Curated Content** / **Original Article**
  - [ ] @bernhold 
  - [ ] @jarrah42 
  - [ ] @pagrubel 
  - [ ] @curfman 
  - [ ] @rinkug 
  - [ ] @bartlettroscoe

**Comment by markcmiller86** [comment]
I do feel fuzzy on the attributes. For example, is *complexity* more a statement about the effort to develop the content or more about the effort in understanding it by a reader once it is published? I am pretty sure we are talking only about the development process here (really the process of *reviewing* a drafted submission). But, then, isn't *quality threshold* encompassed by *complexity*? Certainly a higher *quality threshold* means more effort, doesn't it?

**Comment by jarrah42** [comment]
I like "original" because it clearly distinguishes between what is essentially republished content (curated) and content that has been specifically created for the site.

**Comment by pagrubel** [comment]
I voted for the more explicit terms, as you add people to to team it makes it clearer.

**Comment by bernhold** [comment]
> I do feel fuzzy on the attributes. For example, is _complexity_ more a statement about the effort to develop the content or more about the effort in understanding it by a reader once it is published? I am pretty sure we are talking only about the development process here (really the process of _reviewing_ a drafted submission). But, then, isn't _quality threshold_ encompassed by _complexity_? Certainly a higher _quality threshold_ means more effort, doesn't it?

For me, *complexity* has to do with the technical complexity of the material.  I think complexity and originality are likely to have some correlation, but I don't think they're the same.

The quality threshold is more about what we (BSSw team) want to set as the quality levels for different parts of the site.  So blog articles are something we draw attention to and advertise, so we want them to be relatively high quality.  Other kinds of original content might be a little lower.  Events, being ephemeral, don't need to be especially high.

**Comment by markcmiller86** [comment]
@curfman @rinkug and @bartlettroscoe ... reminder. I've asked for a vote on content type names [here](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/pull/373#issuecomment-497764644). Please indicate your vote by checking a box in one or the other list.

**Comment by bartlettroscoe** [comment]
I voted for "Event / Curated Content / Original Article".  More explicit.

**Comment by markcmiller86** [comment]
Ok, I've updated content type names based on votes, above.

**Comment by markcmiller86** [comment]
I've forgotten that I left this in draft mode. I just now  took out of draft and so a number of people have been asked to review but I also just now pared that list down to three trying to spare Lois, David and Ross any work in reviewing.

**Comment by bartlettroscoe** [comment]
@markcmiller86, last commits were from 6/6/2019.  What is there new to review?

**Comment by markcmiller86** [comment]
@bernhold and @rinkug if this still captures useful information we want to maintain, lets go ahead and sign off on this PR. Otherwise, lemme know and we can close it.

**Comment by markcmiller86** [comment]
@rinku and @bernhold am wondering if this is still relevant? The goal was to define our content types. If you think its relevant *and* the proposed description(s) are ok, please approve.

**Pull request merged**
